# automatically generated by the FlatBuffers compiler, do not modify

# namespace: club

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WhenISaySo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WhenISaySo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWhenISaySo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WhenISaySo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def WhenISaySoStart(builder):
    builder.StartObject(0)

def Start(builder):
    WhenISaySoStart(builder)

def WhenISaySoEnd(builder):
    return builder.EndObject()

def End(builder):
    return WhenISaySoEnd(builder)
