// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.bots

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CreateContractResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CreateContractResponse {
        __init(_i, _bb)
        return this
    }
    val contractName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val contractNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun contractNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_24_3_25()
        fun getRootAsCreateContractResponse(_bb: ByteBuffer): CreateContractResponse = getRootAsCreateContractResponse(_bb, CreateContractResponse())
        fun getRootAsCreateContractResponse(_bb: ByteBuffer, obj: CreateContractResponse): CreateContractResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCreateContractResponse(builder: FlatBufferBuilder, contractNameOffset: Int) : Int {
            builder.startTable(1)
            addContractName(builder, contractNameOffset)
            return endCreateContractResponse(builder)
        }
        fun startCreateContractResponse(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addContractName(builder: FlatBufferBuilder, contractName: Int) = builder.addOffset(0, contractName, 0)
        fun endCreateContractResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
