# automatically generated by the FlatBuffers compiler, do not modify

# namespace: firmware

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FirmwareChallengeRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FirmwareChallengeRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFirmwareChallengeRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FirmwareChallengeRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FirmwareChallengeRequest
    def Nonce(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FirmwareChallengeRequest
    def NonceAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FirmwareChallengeRequest
    def NonceLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FirmwareChallengeRequest
    def NonceIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FirmwareChallengeRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    FirmwareChallengeRequestStart(builder)

def FirmwareChallengeRequestAddNonce(builder, nonce):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(nonce), 0)

def AddNonce(builder, nonce):
    FirmwareChallengeRequestAddNonce(builder, nonce)

def FirmwareChallengeRequestStartNonceVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartNonceVector(builder, numElems):
    return FirmwareChallengeRequestStartNonceVector(builder, numElems)

def FirmwareChallengeRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return FirmwareChallengeRequestEnd(builder)
