# automatically generated by the FlatBuffers compiler, do not modify

# namespace: firmware

class MessagePayload(object):
    NONE = 0
    FirmwareChallengeRequest = 1
    FirmwareChallengeResponse = 2
    GetLatestFirmwareRequest = 3
    GetLatestFirmwareResponse = 4
    GetFirmwareChunkRequest = 5
    GetFirmwareChunkResponse = 6
