// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client_hello.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package club.subjugated.proto.message;

@kotlin.jvm.JvmName("-initializeauthenticated")
public inline fun authenticated(block: club.subjugated.proto.message.AuthenticatedKt.Dsl.() -> kotlin.Unit): club.subjugated.proto.message.ClientHelloOuterClass.Authenticated =
  club.subjugated.proto.message.AuthenticatedKt.Dsl._create(club.subjugated.proto.message.ClientHelloOuterClass.Authenticated.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `club.subjugated.proto.message.Authenticated`
 */
public object AuthenticatedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: club.subjugated.proto.message.ClientHelloOuterClass.Authenticated.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: club.subjugated.proto.message.ClientHelloOuterClass.Authenticated.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): club.subjugated.proto.message.ClientHelloOuterClass.Authenticated = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.success
      @JvmName("setSuccess")
      set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun club.subjugated.proto.message.ClientHelloOuterClass.Authenticated.copy(block: `club.subjugated.proto.message`.AuthenticatedKt.Dsl.() -> kotlin.Unit): club.subjugated.proto.message.ClientHelloOuterClass.Authenticated =
  `club.subjugated.proto.message`.AuthenticatedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

