// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.message.firmware

@Suppress("unused")
class MessagePayload private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val FirmwareChallengeRequest: UByte = 1u
        const val FirmwareChallengeResponse: UByte = 2u
        const val GetLatestFirmwareRequest: UByte = 3u
        const val GetLatestFirmwareResponse: UByte = 4u
        const val GetFirmwareChunkRequest: UByte = 5u
        const val GetFirmwareChunkResponse: UByte = 6u
    }
}
