# automatically generated by the FlatBuffers compiler, do not modify

# namespace: event

class EventType(object):
    Undefined = 0
    AcceptContract = 1
    LocalLock = 2
    LocalUnlock = 3
    Lock = 4
    Unlock = 5
    ReleaseContract = 6
