// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.message.firmware

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class GetLatestFirmwareRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : GetLatestFirmwareRequest {
        __init(_i, _bb)
        return this
    }
    val version : club.subjugated.fb.message.firmware.Version? get() = version(club.subjugated.fb.message.firmware.Version())
    fun version(obj: club.subjugated.fb.message.firmware.Version) : club.subjugated.fb.message.firmware.Version? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_24_3_25()
        fun getRootAsGetLatestFirmwareRequest(_bb: ByteBuffer): GetLatestFirmwareRequest = getRootAsGetLatestFirmwareRequest(_bb, GetLatestFirmwareRequest())
        fun getRootAsGetLatestFirmwareRequest(_bb: ByteBuffer, obj: GetLatestFirmwareRequest): GetLatestFirmwareRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createGetLatestFirmwareRequest(builder: FlatBufferBuilder, versionOffset: Int) : Int {
            builder.startTable(1)
            addVersion(builder, versionOffset)
            return endGetLatestFirmwareRequest(builder)
        }
        fun startGetLatestFirmwareRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addVersion(builder: FlatBufferBuilder, version: Int) = builder.addOffset(0, version, 0)
        fun endGetLatestFirmwareRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
