// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { TimeEndCondition } from '../../subjugated/club/time-end-condition.js';
import { WhenISaySo } from '../../subjugated/club/when-isay-so.js';


export enum EndCondition {
  NONE = 0,
  TimeEndCondition = 1,
  WhenISaySo = 2
}

export function unionToEndCondition(
  type: EndCondition,
  accessor: (obj:TimeEndCondition|WhenISaySo) => TimeEndCondition|WhenISaySo|null
): TimeEndCondition|WhenISaySo|null {
  switch(EndCondition[type]) {
    case 'NONE': return null; 
    case 'TimeEndCondition': return accessor(new TimeEndCondition())! as TimeEndCondition;
    case 'WhenISaySo': return accessor(new WhenISaySo())! as WhenISaySo;
    default: return null;
  }
}

export function unionListToEndCondition(
  type: EndCondition, 
  accessor: (index: number, obj:TimeEndCondition|WhenISaySo) => TimeEndCondition|WhenISaySo|null, 
  index: number
): TimeEndCondition|WhenISaySo|null {
  switch(EndCondition[type]) {
    case 'NONE': return null; 
    case 'TimeEndCondition': return accessor(index, new TimeEndCondition())! as TimeEndCondition;
    case 'WhenISaySo': return accessor(index, new WhenISaySo())! as WhenISaySo;
    default: return null;
  }
}
