// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LockUpdateEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LockUpdateEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLockUpdateEvent(bb:flatbuffers.ByteBuffer, obj?:LockUpdateEvent):LockUpdateEvent {
  return (obj || new LockUpdateEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLockUpdateEvent(bb:flatbuffers.ByteBuffer, obj?:LockUpdateEvent):LockUpdateEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LockUpdateEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startLockUpdateEvent(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endLockUpdateEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLockUpdateEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  LockUpdateEvent.startLockUpdateEvent(builder);
  return LockUpdateEvent.endLockUpdateEvent(builder);
}
}
