// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Contract } from '../../subjugated/club/contract.js';


export enum MessagePayload {
  NONE = 0,
  Contract = 1
}

export function unionToMessagePayload(
  type: MessagePayload,
  accessor: (obj:Contract) => Contract|null
): Contract|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'Contract': return accessor(new Contract())! as Contract;
    default: return null;
  }
}

export function unionListToMessagePayload(
  type: MessagePayload, 
  accessor: (index: number, obj:Contract) => Contract|null, 
  index: number
): Contract|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'Contract': return accessor(index, new Contract())! as Contract;
    default: return null;
  }
}
