// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SessionStart {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SessionStart {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSessionStart(bb:flatbuffers.ByteBuffer, obj?:SessionStart):SessionStart {
  return (obj || new SessionStart()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSessionStart(bb:flatbuffers.ByteBuffer, obj?:SessionStart):SessionStart {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SessionStart()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

publicKey(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

publicKeyLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

publicKeyArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

sessionToken():string|null
sessionToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sessionToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSessionStart(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPublicKey(builder:flatbuffers.Builder, publicKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, publicKeyOffset, 0);
}

static createPublicKeyVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPublicKeyVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addSessionToken(builder:flatbuffers.Builder, sessionTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sessionTokenOffset, 0);
}

static endSessionStart(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSessionStart(builder:flatbuffers.Builder, publicKeyOffset:flatbuffers.Offset, sessionTokenOffset:flatbuffers.Offset):flatbuffers.Offset {
  SessionStart.startSessionStart(builder);
  SessionStart.addPublicKey(builder, publicKeyOffset);
  SessionStart.addSessionToken(builder, sessionTokenOffset);
  return SessionStart.endSessionStart(builder);
}
}
