// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class WhenISaySo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WhenISaySo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWhenISaySo(bb:flatbuffers.ByteBuffer, obj?:WhenISaySo):WhenISaySo {
  return (obj || new WhenISaySo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWhenISaySo(bb:flatbuffers.ByteBuffer, obj?:WhenISaySo):WhenISaySo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WhenISaySo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startWhenISaySo(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endWhenISaySo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWhenISaySo(builder:flatbuffers.Builder):flatbuffers.Offset {
  WhenISaySo.startWhenISaySo(builder);
  return WhenISaySo.endWhenISaySo(builder);
}
}
