# automatically generated by the FlatBuffers compiler, do not modify

# namespace: club

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WebHook(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WebHook()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWebHook(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WebHook
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WebHook
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WebHookStart(builder):
    builder.StartObject(1)

def Start(builder):
    WebHookStart(builder)

def WebHookAddAddress(builder, address):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)

def AddAddress(builder, address):
    WebHookAddAddress(builder, address)

def WebHookEnd(builder):
    return builder.EndObject()

def End(builder):
    return WebHookEnd(builder)
