# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bots

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CreateCommandResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CreateCommandResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCreateCommandResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CreateCommandResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CreateCommandResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from club.subjugated.fb.bots.Error import Error
            obj = Error()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CreateCommandResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    CreateCommandResponseStart(builder)

def CreateCommandResponseAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    CreateCommandResponseAddError(builder, error)

def CreateCommandResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return CreateCommandResponseEnd(builder)
