# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bots

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CreateContractResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CreateContractResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCreateContractResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CreateContractResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CreateContractResponseStart(builder):
    builder.StartObject(0)

def Start(builder):
    CreateContractResponseStart(builder)

def CreateContractResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return CreateContractResponseEnd(builder)
