# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bots

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CreateMessageRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CreateMessageRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCreateMessageRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CreateMessageRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CreateMessageRequest
    def ContractName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CreateMessageRequest
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CreateMessageRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    CreateMessageRequestStart(builder)

def CreateMessageRequestAddContractName(builder, contractName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(contractName), 0)

def AddContractName(builder, contractName):
    CreateMessageRequestAddContractName(builder, contractName)

def CreateMessageRequestAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    CreateMessageRequestAddMessage(builder, message)

def CreateMessageRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return CreateMessageRequestEnd(builder)
