# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bots

class MessagePayload(object):
    NONE = 0
    GetContractRequest = 1
    GetContractResponse = 2
    CreateCommandRequest = 3
    CreateCommandResponse = 4
    CreateContractRequest = 5
    CreateContractResponse = 6
