# automatically generated by the FlatBuffers compiler, do not modify

# namespace: message

class MessagePayload(object):
    NONE = 0
    Contract = 1
    LockCommand = 2
    UnlockCommand = 3
    ReleaseCommand = 4
    StartedUpdate = 5
    PeriodicUpdate = 6
    Acknowledgement = 7
    Error = 8
    AbortCommand = 9
    ResetCommand = 10
