# automatically generated by the FlatBuffers compiler, do not modify

# namespace: message

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Permission(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Permission()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPermission(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Permission
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Permission
    def ReceiveEvents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Permission
    def CanUnlock(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Permission
    def CanRelease(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PermissionStart(builder):
    builder.StartObject(3)

def Start(builder):
    PermissionStart(builder)

def PermissionAddReceiveEvents(builder, receiveEvents):
    builder.PrependBoolSlot(0, receiveEvents, 0)

def AddReceiveEvents(builder, receiveEvents):
    PermissionAddReceiveEvents(builder, receiveEvents)

def PermissionAddCanUnlock(builder, canUnlock):
    builder.PrependBoolSlot(1, canUnlock, 0)

def AddCanUnlock(builder, canUnlock):
    PermissionAddCanUnlock(builder, canUnlock)

def PermissionAddCanRelease(builder, canRelease):
    builder.PrependBoolSlot(2, canRelease, 0)

def AddCanRelease(builder, canRelease):
    PermissionAddCanRelease(builder, canRelease)

def PermissionEnd(builder):
    return builder.EndObject()

def End(builder):
    return PermissionEnd(builder)
