// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LockCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LockCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLockCommand(bb:flatbuffers.ByteBuffer, obj?:LockCommand):LockCommand {
  return (obj || new LockCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLockCommand(bb:flatbuffers.ByteBuffer, obj?:LockCommand):LockCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LockCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startLockCommand(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endLockCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLockCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  LockCommand.startLockCommand(builder);
  return LockCommand.endLockCommand(builder);
}
}
