// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UnlockCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnlockCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnlockCommand(bb:flatbuffers.ByteBuffer, obj?:UnlockCommand):UnlockCommand {
  return (obj || new UnlockCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnlockCommand(bb:flatbuffers.ByteBuffer, obj?:UnlockCommand):UnlockCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnlockCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUnlockCommand(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUnlockCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnlockCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  UnlockCommand.startUnlockCommand(builder);
  return UnlockCommand.endUnlockCommand(builder);
}
}
