// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CreateContractResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreateContractResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreateContractResponse(bb:flatbuffers.ByteBuffer, obj?:CreateContractResponse):CreateContractResponse {
  return (obj || new CreateContractResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreateContractResponse(bb:flatbuffers.ByteBuffer, obj?:CreateContractResponse):CreateContractResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreateContractResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

contractName():string|null
contractName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contractName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCreateContractResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addContractName(builder:flatbuffers.Builder, contractNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, contractNameOffset, 0);
}

static endCreateContractResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreateContractResponse(builder:flatbuffers.Builder, contractNameOffset:flatbuffers.Offset):flatbuffers.Offset {
  CreateContractResponse.startCreateContractResponse(builder);
  CreateContractResponse.addContractName(builder, contractNameOffset);
  return CreateContractResponse.endCreateContractResponse(builder);
}
}
