// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CreateMessageResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreateMessageResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreateMessageResponse(bb:flatbuffers.ByteBuffer, obj?:CreateMessageResponse):CreateMessageResponse {
  return (obj || new CreateMessageResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreateMessageResponse(bb:flatbuffers.ByteBuffer, obj?:CreateMessageResponse):CreateMessageResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreateMessageResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startCreateMessageResponse(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endCreateMessageResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreateMessageResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  CreateMessageResponse.startCreateMessageResponse(builder);
  return CreateMessageResponse.endCreateMessageResponse(builder);
}
}
