// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CreateMessageRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreateMessageRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreateMessageRequest(bb:flatbuffers.ByteBuffer, obj?:CreateMessageRequest):CreateMessageRequest {
  return (obj || new CreateMessageRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreateMessageRequest(bb:flatbuffers.ByteBuffer, obj?:CreateMessageRequest):CreateMessageRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreateMessageRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

contractName():string|null
contractName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contractName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCreateMessageRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addContractName(builder:flatbuffers.Builder, contractNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, contractNameOffset, 0);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endCreateMessageRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreateMessageRequest(builder:flatbuffers.Builder, contractNameOffset:flatbuffers.Offset, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  CreateMessageRequest.startCreateMessageRequest(builder);
  CreateMessageRequest.addContractName(builder, contractNameOffset);
  CreateMessageRequest.addMessage(builder, messageOffset);
  return CreateMessageRequest.endCreateMessageRequest(builder);
}
}
