// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Error } from '../../../../club/subjugated/fb/bots/error.js';


export class CreateCommandResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreateCommandResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreateCommandResponse(bb:flatbuffers.ByteBuffer, obj?:CreateCommandResponse):CreateCommandResponse {
  return (obj || new CreateCommandResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreateCommandResponse(bb:flatbuffers.ByteBuffer, obj?:CreateCommandResponse):CreateCommandResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreateCommandResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

error(obj?:Error):Error|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Error()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCreateCommandResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, errorOffset, 0);
}

static endCreateCommandResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreateCommandResponse(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  CreateCommandResponse.startCreateCommandResponse(builder);
  CreateCommandResponse.addError(builder, errorOffset);
  return CreateCommandResponse.endCreateCommandResponse(builder);
}
}
