// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetLockSessionRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetLockSessionRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetLockSessionRequest(bb:flatbuffers.ByteBuffer, obj?:GetLockSessionRequest):GetLockSessionRequest {
  return (obj || new GetLockSessionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetLockSessionRequest(bb:flatbuffers.ByteBuffer, obj?:GetLockSessionRequest):GetLockSessionRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetLockSessionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shareableToken():string|null
shareableToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shareableToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGetLockSessionRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addShareableToken(builder:flatbuffers.Builder, shareableTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, shareableTokenOffset, 0);
}

static endGetLockSessionRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetLockSessionRequest(builder:flatbuffers.Builder, shareableTokenOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetLockSessionRequest.startGetLockSessionRequest(builder);
  GetLockSessionRequest.addShareableToken(builder, shareableTokenOffset);
  return GetLockSessionRequest.endGetLockSessionRequest(builder);
}
}
