// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CreateCommandRequest } from '../../../../club/subjugated/fb/bots/create-command-request.js';
import { CreateCommandResponse } from '../../../../club/subjugated/fb/bots/create-command-response.js';
import { CreateContractRequest } from '../../../../club/subjugated/fb/bots/create-contract-request.js';
import { CreateContractResponse } from '../../../../club/subjugated/fb/bots/create-contract-response.js';
import { CreateMessageRequest } from '../../../../club/subjugated/fb/bots/create-message-request.js';
import { CreateMessageResponse } from '../../../../club/subjugated/fb/bots/create-message-response.js';
import { GetContractRequest } from '../../../../club/subjugated/fb/bots/get-contract-request.js';
import { GetContractResponse } from '../../../../club/subjugated/fb/bots/get-contract-response.js';
import { GetLockSessionRequest } from '../../../../club/subjugated/fb/bots/get-lock-session-request.js';
import { GetLockSessionResponse } from '../../../../club/subjugated/fb/bots/get-lock-session-response.js';


export enum MessagePayload {
  NONE = 0,
  GetContractRequest = 1,
  GetContractResponse = 2,
  CreateCommandRequest = 3,
  CreateCommandResponse = 4,
  CreateContractRequest = 5,
  CreateContractResponse = 6,
  GetLockSessionRequest = 7,
  GetLockSessionResponse = 8,
  CreateMessageRequest = 9,
  CreateMessageResponse = 10
}

export function unionToMessagePayload(
  type: MessagePayload,
  accessor: (obj:CreateCommandRequest|CreateCommandResponse|CreateContractRequest|CreateContractResponse|CreateMessageRequest|CreateMessageResponse|GetContractRequest|GetContractResponse|GetLockSessionRequest|GetLockSessionResponse) => CreateCommandRequest|CreateCommandResponse|CreateContractRequest|CreateContractResponse|CreateMessageRequest|CreateMessageResponse|GetContractRequest|GetContractResponse|GetLockSessionRequest|GetLockSessionResponse|null
): CreateCommandRequest|CreateCommandResponse|CreateContractRequest|CreateContractResponse|CreateMessageRequest|CreateMessageResponse|GetContractRequest|GetContractResponse|GetLockSessionRequest|GetLockSessionResponse|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'GetContractRequest': return accessor(new GetContractRequest())! as GetContractRequest;
    case 'GetContractResponse': return accessor(new GetContractResponse())! as GetContractResponse;
    case 'CreateCommandRequest': return accessor(new CreateCommandRequest())! as CreateCommandRequest;
    case 'CreateCommandResponse': return accessor(new CreateCommandResponse())! as CreateCommandResponse;
    case 'CreateContractRequest': return accessor(new CreateContractRequest())! as CreateContractRequest;
    case 'CreateContractResponse': return accessor(new CreateContractResponse())! as CreateContractResponse;
    case 'GetLockSessionRequest': return accessor(new GetLockSessionRequest())! as GetLockSessionRequest;
    case 'GetLockSessionResponse': return accessor(new GetLockSessionResponse())! as GetLockSessionResponse;
    case 'CreateMessageRequest': return accessor(new CreateMessageRequest())! as CreateMessageRequest;
    case 'CreateMessageResponse': return accessor(new CreateMessageResponse())! as CreateMessageResponse;
    default: return null;
  }
}

export function unionListToMessagePayload(
  type: MessagePayload, 
  accessor: (index: number, obj:CreateCommandRequest|CreateCommandResponse|CreateContractRequest|CreateContractResponse|CreateMessageRequest|CreateMessageResponse|GetContractRequest|GetContractResponse|GetLockSessionRequest|GetLockSessionResponse) => CreateCommandRequest|CreateCommandResponse|CreateContractRequest|CreateContractResponse|CreateMessageRequest|CreateMessageResponse|GetContractRequest|GetContractResponse|GetLockSessionRequest|GetLockSessionResponse|null, 
  index: number
): CreateCommandRequest|CreateCommandResponse|CreateContractRequest|CreateContractResponse|CreateMessageRequest|CreateMessageResponse|GetContractRequest|GetContractResponse|GetLockSessionRequest|GetLockSessionResponse|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'GetContractRequest': return accessor(index, new GetContractRequest())! as GetContractRequest;
    case 'GetContractResponse': return accessor(index, new GetContractResponse())! as GetContractResponse;
    case 'CreateCommandRequest': return accessor(index, new CreateCommandRequest())! as CreateCommandRequest;
    case 'CreateCommandResponse': return accessor(index, new CreateCommandResponse())! as CreateCommandResponse;
    case 'CreateContractRequest': return accessor(index, new CreateContractRequest())! as CreateContractRequest;
    case 'CreateContractResponse': return accessor(index, new CreateContractResponse())! as CreateContractResponse;
    case 'GetLockSessionRequest': return accessor(index, new GetLockSessionRequest())! as GetLockSessionRequest;
    case 'GetLockSessionResponse': return accessor(index, new GetLockSessionResponse())! as GetLockSessionResponse;
    case 'CreateMessageRequest': return accessor(index, new CreateMessageRequest())! as CreateMessageRequest;
    case 'CreateMessageResponse': return accessor(index, new CreateMessageResponse())! as CreateMessageResponse;
    default: return null;
  }
}
