// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.message

@Suppress("unused")
class Capabilities private constructor() {
    companion object {
        const val Online: Byte = 1
        const val Time: Byte = 2
    }
}
