// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.message

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Command : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Command {
        __init(_i, _bb)
        return this
    }
    fun publicKey(j: Int) : UByte {
        val o = __offset(4)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val publicKeyLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val publicKeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun publicKeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val session : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sessionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun sessionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val body : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val bodyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun bodyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val contract : club.subjugated.fb.message.Contract? get() = contract(club.subjugated.fb.message.Contract())
    fun contract(obj: club.subjugated.fb.message.Contract) : club.subjugated.fb.message.Contract? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val commandType : Byte
        get() {
            val o = __offset(12)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_24_3_25()
        fun getRootAsCommand(_bb: ByteBuffer): Command = getRootAsCommand(_bb, Command())
        fun getRootAsCommand(_bb: ByteBuffer, obj: Command): Command {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCommand(builder: FlatBufferBuilder, publicKeyOffset: Int, sessionOffset: Int, bodyOffset: Int, contractOffset: Int, commandType: Byte) : Int {
            builder.startTable(5)
            addContract(builder, contractOffset)
            addBody(builder, bodyOffset)
            addSession(builder, sessionOffset)
            addPublicKey(builder, publicKeyOffset)
            addCommandType(builder, commandType)
            return endCommand(builder)
        }
        fun startCommand(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addPublicKey(builder: FlatBufferBuilder, publicKey: Int) = builder.addOffset(0, publicKey, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createPublicKeyVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startPublicKeyVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addSession(builder: FlatBufferBuilder, session: Int) = builder.addOffset(1, session, 0)
        fun addBody(builder: FlatBufferBuilder, body: Int) = builder.addOffset(2, body, 0)
        fun addContract(builder: FlatBufferBuilder, contract: Int) = builder.addOffset(3, contract, 0)
        fun addCommandType(builder: FlatBufferBuilder, commandType: Byte) = builder.addByte(4, commandType, 0)
        fun endCommand(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
