// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.message

@Suppress("unused")
class CommandType private constructor() {
    companion object {
        const val Undefined: Byte = 0
        const val AcceptContract: Byte = 1
        const val Lock: Byte = 2
        const val Unlock: Byte = 3
        const val Release: Byte = 4
        const val Ping: Byte = 5
    }
}
