// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.message

@Suppress("unused")
class EndCondition private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val TimeEndCondition: UByte = 1u
        const val WhenISaySo: UByte = 2u
    }
}
