// automatically generated by the FlatBuffers compiler, do not modify

package club.subjugated.fb.message

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Event : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Event {
        __init(_i, _bb)
        return this
    }
    val metadata : club.subjugated.fb.message.CommonMetadata? get() = metadata(club.subjugated.fb.message.CommonMetadata())
    fun metadata(obj: club.subjugated.fb.message.CommonMetadata) : club.subjugated.fb.message.CommonMetadata? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val eventType : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_24_3_25()
        fun getRootAsEvent(_bb: ByteBuffer): Event = getRootAsEvent(_bb, Event())
        fun getRootAsEvent(_bb: ByteBuffer, obj: Event): Event {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEvent(builder: FlatBufferBuilder, metadataOffset: Int, eventType: Byte) : Int {
            builder.startTable(2)
            addMetadata(builder, metadataOffset)
            addEventType(builder, eventType)
            return endEvent(builder)
        }
        fun startEvent(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addMetadata(builder: FlatBufferBuilder, metadata: Int) = builder.addOffset(0, metadata, 0)
        fun addEventType(builder: FlatBufferBuilder, eventType: Byte) = builder.addByte(1, eventType, 0)
        fun endEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
